### ISSUE TITLE
[IssueSelector] EnterでIssue内容を見れるようにしたい

### ISSUE THREAD

**Issue by yamamoto-yuta** [ShotaroKataoka/Fuzzy-Git-Operator#115]
今だとEnterでコマンドラインにIssue番号が入る仕様ですけどそれは別のkeybindにして，EnterではIssue内容が見れた方がいいかなーと思いました．

イメージとしては↓みたいな感じです．
```
$ gh issue list | fzf | cut -f 1 | xargs -I % gh issue view %
```

参考記事：
https://blog.takanabe.tokyo/2020/04/github-cli-%E3%81%AF-hub-%E3%81%AE%E4%BB%A3%E3%82%8F%E3%82%8A%E3%81%AB%E3%81%AA%E3%82%8B%E3%81%8B/

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
たしかに
ふつうのviewの方がいい？
previewで作ったやつの方がいい？

**Comment by ShotaroKataoka** [comment]
ふつうのviewだとコメントは最新のみ表示
情報が詳しい部分がある(パイプだと省略される情報がある)
個人的には見にくくね？って思ったりも

Previewはあの感じ
特定条件下で表示が崩れる可能性あり(コメント内容によってはパースをミスる)
見た目はこっちのが好み

**Comment by yamamoto-yuta** [comment]
previewで作ったやつの方がいいですね．Issue内容の流れが見れた方が良いし，見やすさもこちらの方が良いので．

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
OKです！
なるべくpagerで表示できるように頑張ります！(色つけれるかな.......)
