### ISSUE TITLE
[github] issue comment機能

### ISSUE THREAD

**Issue by ShotaroKataoka** [ShotaroKataoka/Fuzzy-Git-Operator#139]
## 内容要約
issue selectorでコメントできるようにする

## 理由・詳細
GIthub CLI 1.5.0で対応された
https://github.com/cli/cli/releases

**Comment by ShotaroKataoka** [comment]
test comment

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta
This is fgo issue comment test.
hey you.

**Comment by ShotaroKataoka** [comment]
saving comment test

ok!

**Comment by yamamoto-yuta** [comment]
issue comment test

**Comment by ShotaroKataoka** [comment]
issue selectorでコメントできるようにする

**Comment by ShotaroKataoka** [comment]
aa
test comment
aa

**Comment by ShotaroKataoka** [comment]
aa
test comment
aa

**Comment by ShotaroKataoka** [comment]
aa
test comment
aa

**Comment by ShotaroKataoka** [comment]
aa
test comment
aa

**Comment by ShotaroKataoka** [comment]
close test

**Comment by yamamoto-yuta** [comment]
# issue comment test
- hogehoge
