### ISSUE TITLE
[IssuePreview] View issueのPreviewをきれいにする

### ISSUE THREAD

**Issue by yamamoto-yuta** [ShotaroKataoka/Fuzzy-Git-Operator#97]
fetのbeautifulモード的な？

**Comment by ShotaroKataoka** [comment]
どうすれば見やすくなると思いますか？

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
どうすれば見やすくなると思う？

**Comment by yamamoto-yuta** [comment]
こんな感じのはどうですか？

```
yamamoto-yuta commented on 26 Nov
╭──────────────────────────────────────────────────────────────────────────────╮
│ 🌆 image                                                                     │
╰──────────────────────────────────────────────────────────────────────────────╯

yamamoto-yuta added bug need survey labels on 26 Nov

yamamoto-yuta commented on 26 Nov
╭──────────────────────────────────────────────────────────────────────────────╮
│ これ試したけどダメだった…                                                    │
│ https://qiita.com/teruo-oshida/items/cd2df6c3af6a3888f06e                    │
│                                                                              │
│ ┌──────────────────────────────────────────────────────────────────────────┐ │
│ │ docker-compose exec <SERVICE_NAME> sh -c "$(source setuptty.sh); exec b  │ │
│ └──────────────────────────────────────────────────────────────────────────┘ │
╰──────────────────────────────────────────────────────────────────────────────╯
```

コード：
---
console = Console()



text1 = """
![image](https://user-images.githubusercontent.com/55144709/100355414-0c23ba00-3035-11eb-8f4b-d6e9ff9b599b.png)
"""
text1 = Panel(Markdown(text1))

text2 = """
これ試したけどダメだった…
https://qiita.com/teruo-oshida/items/cd2df6c3af6a3888f06e

```
docker-compose exec <SERVICE_NAME> sh -c "$(source setuptty.sh); exec bash -l"
```
"""
text2 = Panel(Markdown(text2))

code = RenderGroup(
    "yamamoto-yuta commented on 26 Nov",
    text1,
    "",
    "yamamoto-yuta added bug need survey labels on 26 Nov",
    "",
    "yamamoto-yuta commented on 26 Nov",
    text2
    )
console.print(code)

**Comment by ShotaroKataoka** [comment]
確認してなかった
いいねこれ！

previewの中だから外部コマンド作った方がいいかも．．？

確認する前に作ったやつ（previewにはなってない）
![image](https://user-images.githubusercontent.com/42331656/103415656-7dbbce80-4bc6-11eb-8909-d82827e21b32.png)

色付けただけ
markdownの方がよさそう

もしくはsyntax

**Comment by yamamoto-yuta** [comment]
Previewの中ってのが厄介ですね…単純にやるならMarkdownですかね…

**Comment by ShotaroKataoka** [comment]
markdownにするにはテキストを整形しないとなんだよねー

外部ファイルでスクリプト書いてみるわ

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
Markdownのなかでも色つけれる仕組みあったらいいね

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
ちな
gh issue view 45
と
gh issue view 45 | hogehoge
じゃ出力が異なるっぽい
git系は他のコマンドもだいたいそうだけど

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
#101 これどうすか？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
確認しました！

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
今回の実装でpreviewの中身は実行ファイルにしちゃえばなんでもできることが分かった
echoを分けて行えば逐次的に表示してくれるし使いやすい
メンテナンス性もよくなる

bindもそうだと思う
